<?php

namespace SEOBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SEOBundle\Entity\Meta;

/**
 * MetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaRepository extends EntityRepository
{

    /**
     * @param $id
     * @return Meta|null
     */
    public function findOne($id)
    {
        return $this->getRepository('ApiBundle:Meta')
            ->createQueryBuilder('o')
            ->select('o')
            ->where('o.id = :id')
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->setCacheable($this->isCacheEnabled())
            //->useResultCache($this->isCacheEnabled(), $this->getCacheLifetime(), 'meta_id_' . $id)
            ->getOneOrNullResult();

    }

    /**
     * @param $name
     * @return EntityRepository
     */
    protected function getRepository($name)
    {
        return $this->getEntityManager()->getRepository($name);
    }

    /**
     * @return bool
     */
    protected function isCacheEnabled()
    {
        if (class_exists('\Constants')) {
            return \Constants::$USE_DATABASE_CACHE;
        }
        return false;
    }

    /**
     * @return bool
     */
    protected function getCacheLifetime()
    {
        if (class_exists('\Constants')) {
            return \Constants::$DATABASE_CACHE_LIFETIME;
        }
        return 1;
    }

}
